version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: search-for-books
    ports:
      - "80:80"
    image: search-for-books:1.0.0-prod
    volumes:
      - .:/client
    environment:
      - NODE_ENV=production