version: '3.8'
services:
  client:
    build:
      context: ./client
    container_name: client_search_books
    ports:
      - "3000:3000"
    image: search-for-books
    volumes:
      - .:/client
    environment:
      - NODE_ENV=production