version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: search-for-books
    ports:
      - "3000:80"

    image: simple_google_search_books:1.0.0-prod
    volumes:
      - .:/client
    #  - etc-letsencrypt:/etc/letsencrypt
    #  - backend:/backend/certbot
    environment:
      - NODE_ENV=production

  #certbot:
  #  depends_on:
  #    - client
   # image: certbot/certbot
  #  container_name: certbot
  #  restart: unless-stopped
  #  volumes:
   #   - etc-letsencrypt:/etc/letsencrypt
   #   - backend:/backend/certbot
   # command: certonly --webroot --webroot-path=/backend/certbot
    #  --agree-tos --no-eff-email --email Petakioto2.0@gmail.com --dry-run -d www.simplegooglesearchbooks.org

#volumes:
#  backend:
#  etc-letsencrypt:
#networks:
#  search-for-books:
#    driver: bridge